server.port=8080

# gRPC inventory target
inventory.addr=${INVENTORY_ADDR:inventory:50051}
grpc.deadline.ms=${GRPC_DEADLINE_MS:3000}

# OTel
otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://lgtm:4318}
otel.service.name=${OTEL_SERVICE_NAME:order-service}
