FROM registry.access.redhat.com/ubi9/dotnet-100 AS build
USER root
WORKDIR /src
COPY RouterService/RouterService.csproj RouterService/
RUN dotnet restore RouterService/RouterService.csproj
COPY RouterService/ RouterService/
RUN dotnet publish RouterService/RouterService.csproj -c Release -o /app

FROM registry.access.redhat.com/ubi9/dotnet-100-aspnet
WORKDIR /app
COPY --from=build /app .
EXPOSE 8080
ENTRYPOINT ["dotnet", "RouterService.dll"]
