quarkus.application.name=cache-service
quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/appdb
quarkus.datasource.username=appuser
quarkus.datasource.password=apppass
quarkus.datasource.jdbc.validation-query-sql=SELECT 1
quarkus.datasource.jdbc.idle-removal-interval=2S

quarkus.redis.hosts=redis://localhost:6379
quarkus.redis.timeout=2s
quarkus.redis.reconnect-attempts=100
quarkus.redis.reconnect-interval=PT1S

cache-service.ttl-seconds=60
cache-service.flush-period=1s
cache-service.refresh-period=5s
cache-service.refresh-before-seconds=10
