quarkus.http.port=8082
quarkus.grpc.server.port=9000
quarkus.grpc.server.use-separate-server=true

quarkus.log.level=INFO
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] %s%e%n

quarkus.otel.enabled=true
quarkus.otel.exporter.otlp.endpoint=http://lgtm:4318
quarkus.otel.service.name=inventory-service
