apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: registry.access.redhat.com/ubi9/python-312:latest
          securityContext:
            runAsUser: 1001
            privileged: false
            readOnlyRootFilesystem: true
