spring:
  application:
    name: gateway
  graphql:
    graphiql:
      enabled: true

server:
  port: 8080

inventory:
  addr: ${INVENTORY_ADDR:inventory:50051}

orderapi:
  url: ${ORDER_API_URL:http://order-api:8081}
