quarkus.http.port=8080

order-api.url=${ORDER_API_URL:http://order-api:8081}

quarkus.grpc.clients.inventory.host=${QUARKUS_GRPC_CLIENTS_INVENTORY_HOST:inventory}
quarkus.grpc.clients.inventory.port=${QUARKUS_GRPC_CLIENTS_INVENTORY_PORT:9000}

quarkus.smallrye-graphql.ui.always-include=true

quarkus.log.level=INFO
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] %s%e%n

quarkus.otel.enabled=true
quarkus.otel.exporter.otlp.endpoint=http://lgtm:4318
quarkus.otel.service.name=gateway
