// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/inventory.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	mi := &file_proto_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *GetStockRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

type GetStockReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Available     int32                  `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockReply) Reset() {
	*x = GetStockReply{}
	mi := &file_proto_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockReply) ProtoMessage() {}

func (x *GetStockReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockReply.ProtoReflect.Descriptor instead.
func (*GetStockReply) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GetStockReply) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *GetStockReply) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

type GetStockBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skus          []string               `protobuf:"bytes,1,rep,name=skus,proto3" json:"skus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockBatchRequest) Reset() {
	*x = GetStockBatchRequest{}
	mi := &file_proto_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockBatchRequest) ProtoMessage() {}

func (x *GetStockBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockBatchRequest.ProtoReflect.Descriptor instead.
func (*GetStockBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetStockBatchRequest) GetSkus() []string {
	if x != nil {
		return x.Skus
	}
	return nil
}

type GetStockBatchReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*GetStockReply       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockBatchReply) Reset() {
	*x = GetStockBatchReply{}
	mi := &file_proto_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockBatchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockBatchReply) ProtoMessage() {}

func (x *GetStockBatchReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockBatchReply.ProtoReflect.Descriptor instead.
func (*GetStockBatchReply) Descriptor() ([]byte, []int) {
	return file_proto_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *GetStockBatchReply) GetItems() []*GetStockReply {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_inventory_proto protoreflect.FileDescriptor

const file_proto_inventory_proto_rawDesc = "" +
	"\n" +
	"\x15proto/inventory.proto\x12\tinventory\"#\n" +
	"\x0fGetStockRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\"?\n" +
	"\rGetStockReply\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\x05R\tavailable\"*\n" +
	"\x14GetStockBatchRequest\x12\x12\n" +
	"\x04skus\x18\x01 \x03(\tR\x04skus\"D\n" +
	"\x12GetStockBatchReply\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.inventory.GetStockReplyR\x05items2\x9e\x01\n" +
	"\tInventory\x12@\n" +
	"\bGetStock\x12\x1a.inventory.GetStockRequest\x1a\x18.inventory.GetStockReply\x12O\n" +
	"\rGetStockBatch\x12\x1f.inventory.GetStockBatchRequest\x1a\x1d.inventory.GetStockBatchReplyB\x05Z\x03pb/b\x06proto3"

var (
	file_proto_inventory_proto_rawDescOnce sync.Once
	file_proto_inventory_proto_rawDescData []byte
)

func file_proto_inventory_proto_rawDescGZIP() []byte {
	file_proto_inventory_proto_rawDescOnce.Do(func() {
		file_proto_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_proto_rawDesc), len(file_proto_inventory_proto_rawDesc)))
	})
	return file_proto_inventory_proto_rawDescData
}

var file_proto_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_inventory_proto_goTypes = []any{
	(*GetStockRequest)(nil),      // 0: inventory.GetStockRequest
	(*GetStockReply)(nil),        // 1: inventory.GetStockReply
	(*GetStockBatchRequest)(nil), // 2: inventory.GetStockBatchRequest
	(*GetStockBatchReply)(nil),   // 3: inventory.GetStockBatchReply
}
var file_proto_inventory_proto_depIdxs = []int32{
	1, // 0: inventory.GetStockBatchReply.items:type_name -> inventory.GetStockReply
	0, // 1: inventory.Inventory.GetStock:input_type -> inventory.GetStockRequest
	2, // 2: inventory.Inventory.GetStockBatch:input_type -> inventory.GetStockBatchRequest
	1, // 3: inventory.Inventory.GetStock:output_type -> inventory.GetStockReply
	3, // 4: inventory.Inventory.GetStockBatch:output_type -> inventory.GetStockBatchReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_inventory_proto_init() }
func file_proto_inventory_proto_init() {
	if File_proto_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_proto_rawDesc), len(file_proto_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_proto_goTypes,
		DependencyIndexes: file_proto_inventory_proto_depIdxs,
		MessageInfos:      file_proto_inventory_proto_msgTypes,
	}.Build()
	File_proto_inventory_proto = out.File
	file_proto_inventory_proto_goTypes = nil
	file_proto_inventory_proto_depIdxs = nil
}
