FROM registry.access.redhat.com/ubi9/dotnet-100 AS build
USER root
WORKDIR /src
COPY NotificationConsumer/NotificationConsumer.csproj NotificationConsumer/
RUN dotnet restore NotificationConsumer/NotificationConsumer.csproj
COPY NotificationConsumer/ NotificationConsumer/
RUN dotnet publish NotificationConsumer/NotificationConsumer.csproj -c Release -o /app

FROM registry.access.redhat.com/ubi9/dotnet-100-aspnet
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "NotificationConsumer.dll"]
