FROM registry.access.redhat.com/ubi9/dotnet-100 AS build
USER root
WORKDIR /src
COPY DecoratorService/DecoratorService.csproj DecoratorService/
RUN dotnet restore DecoratorService/DecoratorService.csproj
COPY DecoratorService/ DecoratorService/
RUN dotnet publish DecoratorService/DecoratorService.csproj -c Release -o /app

FROM registry.access.redhat.com/ubi9/dotnet-100-aspnet
WORKDIR /app
COPY --from=build /app .
EXPOSE 8080
ENTRYPOINT ["dotnet", "DecoratorService.dll"]
