FROM registry.access.redhat.com/ubi9/dotnet-100 AS build
USER root
WORKDIR /src
COPY StubService/StubService.csproj StubService/
RUN dotnet restore StubService/StubService.csproj
COPY StubService/ StubService/
RUN dotnet publish StubService/StubService.csproj -c Release -o /app

FROM registry.access.redhat.com/ubi9/dotnet-100-aspnet
WORKDIR /app
COPY --from=build /app .
EXPOSE 8080
ENTRYPOINT ["dotnet", "StubService.dll"]
