FROM registry.access.redhat.com/ubi9/dotnet-100 AS build
USER root
WORKDIR /src
COPY StreamProcessor/StreamProcessor.csproj StreamProcessor/
RUN dotnet restore StreamProcessor/StreamProcessor.csproj
COPY StreamProcessor/ StreamProcessor/
RUN dotnet publish StreamProcessor/StreamProcessor.csproj -c Release -o /app

FROM registry.access.redhat.com/ubi9/dotnet-100-aspnet
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "StreamProcessor.dll"]
