quarkus.http.port=8080
legacy.url=${LEGACY_URL:http://legacy:8080}
quarkus.redis.hosts=${QUARKUS_REDIS_HOSTS:redis://localhost:6379}

# Outgoing Kafka channel
mp.messaging.outgoing.order-events-out.connector=smallrye-kafka
mp.messaging.outgoing.order-events-out.topic=order.placed
mp.messaging.outgoing.order-events-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
