quarkus.http.port=8080
quarkus.application.name=saga-orchestrator
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/appdb}
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:appuser}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:apppass}
