quarkus.application.name=order-service
quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/appdb
quarkus.datasource.username=appuser
quarkus.datasource.password=apppass
quarkus.datasource.jdbc.validation-query-sql=SELECT 1
quarkus.datasource.jdbc.idle-removal-interval=2S

quarkus.log.category."events".level=INFO
