quarkus.application.name=order-service
quarkus.http.port=8080

grpc.deadline.ms=${GRPC_DEADLINE_MS:3000}

quarkus.grpc.clients.inventory.host=localhost
quarkus.grpc.clients.inventory.port=9000
quarkus.grpc.clients.inventory.plain-text=true

quarkus.otel.exporter.otlp.endpoint=http://localhost:4318
quarkus.otel.exporter.otlp.protocol=http/protobuf
