quarkus.application.name=inventory-service
quarkus.http.port=8081
quarkus.grpc.server.port=9000

initial.stock=${INITIAL_STOCK:10}
fail.mode=${FAIL_MODE:none}

quarkus.otel.exporter.otlp.endpoint=http://localhost:4318
quarkus.otel.exporter.otlp.protocol=http/protobuf
