quarkus.http.host-enabled=false

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:appuser}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:apppass}
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/appdb}

mp.messaging.incoming.order-placed.connector=smallrye-kafka
mp.messaging.incoming.order-placed.topic=order.placed
mp.messaging.incoming.order-placed.group.id=shipping-group
mp.messaging.incoming.order-placed.auto.offset.reset=earliest
mp.messaging.incoming.order-placed.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

quarkus.log.level=INFO
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n

quarkus.otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}
quarkus.application.name=${OTEL_SERVICE_NAME:shipping-consumer}
