spring:
  application:
    name: order-service
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8080

inventory:
  addr: ${INVENTORY_ADDR:inventory:50051}

otel:
  service:
    name: order-service
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://lgtm:4318}
      protocol: http/protobuf

logging:
  pattern:
    console: "%d{ISO8601} %-5level [%thread] %logger{36} - trace_id=%X{trace_id:-} %msg%n"
