quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:appuser}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:apppass}
quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/appdb}

quarkus.grpc.clients.inventory.host=${QUARKUS_GRPC_CLIENTS_INVENTORY_HOST:localhost}
quarkus.grpc.clients.inventory.port=${QUARKUS_GRPC_CLIENTS_INVENTORY_PORT:9000}

mp.messaging.outgoing.order-placed.connector=smallrye-kafka
mp.messaging.outgoing.order-placed.topic=order.placed
mp.messaging.outgoing.order-placed.value.serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

quarkus.log.level=INFO
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) trace_id=%X{trace_id} %s%e%n

quarkus.otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
quarkus.application.name=${OTEL_SERVICE_NAME:order-service}

quarkus.micrometer.export.otlp.url=${MICROMETER_OTLP_URL:http://localhost:4318/v1/metrics}
quarkus.micrometer.export.otlp.resource-attributes.service.name=${OTEL_SERVICE_NAME:order-service}
quarkus.micrometer.export.otlp.step=5s
