quarkus.http.host-enabled=false

mp.messaging.incoming.order-placed.connector=smallrye-kafka
mp.messaging.incoming.order-placed.topic=order.placed
mp.messaging.incoming.order-placed.group.id=stream-processor
mp.messaging.incoming.order-placed.auto.offset.reset=earliest
mp.messaging.incoming.order-placed.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

mp.messaging.outgoing.revenue-out.connector=smallrye-kafka
mp.messaging.outgoing.revenue-out.topic=revenue.by-merchant
mp.messaging.outgoing.revenue-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

window.seconds=${WINDOW_SECONDS:10}

quarkus.log.level=INFO
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n

quarkus.otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}
quarkus.application.name=${OTEL_SERVICE_NAME:stream-processor}
