# gRPC server configuration
quarkus.grpc.server.port=9000
quarkus.http.port=8081

initial.stock=${INITIAL_STOCK:100}

# Logging
quarkus.log.level=INFO
quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n

# OpenTelemetry
quarkus.otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}
quarkus.application.name=${OTEL_SERVICE_NAME:inventory-service}
