quarkus.http.port=8081

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/appdb
quarkus.datasource.username=appuser
quarkus.datasource.password=apppass

quarkus.log.level=INFO
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] %s%e%n

quarkus.otel.enabled=true
quarkus.otel.exporter.otlp.endpoint=http://lgtm:4318
quarkus.otel.service.name=order-api
